add subdir argument
thatfuckingbird/hydownloader pull request #19
Opened 2022-04-25 23:40 UTC by AbbyAbbyAbbyAbby

Add a subdirectory argument to reduce the amount of files/folders that need to be walked when importing specific folders.

2022-04-26 07:29 UTC, thatfuckingbird requested changes

2022-04-26 07:29 UTC, thatfuckingbird commented on hydownloader/importer.py
> +def run_job(path: str, job: str, skip_already_imported: bool, no_skip_on_differing_times: bool, config: Optional[str], verbose: bool, do_it: bool, no_abort_on_missing_metadata: bool, filename_regex:
```suggestion
def run_job(path: str, job: str, skip_already_imported: bool, no_skip_on_differing_times: bool, config: Optional[str], verbose: bool, do_it: bool, no_abort_on_missing_metadata: bool, filename_regex: Optional[str], no_abort_on_error: bool, no_force_add_metadata: bool, force_add_files: bool, subdir: Optional[str]) -> None:
```

2022-04-26 07:29 UTC, thatfuckingbird commented on hydownloader/importer.py
> +@click.option('--subdir', type=str, default=None, show_default=True, help='Only scan a subdirectory within the databases \'gallery-dl\' folder to target specific files. Use this to target specific fo
```suggestion
@click.option('--subdir', type=str, default=None, show_default=True, help='Only scan a subdirectory within the database's \'gallery-dl\' folder to target specific files, e.g. \'gelbooru/tag\' to import a specific gelbooru tag.')
```

2022-04-30 06:36 UTC, AbbyAbbyAbbyAbby commented
Tested and working, want to point out that the `/gallery-dl/` is prepended when using `--subdir` now as I missed that initially.

2022-04-30 09:49 UTC, merged